import { createRef, useEffect } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import styles from "@/styles/Breathe.module.css";
import lottie from "lottie-web";
import NavBar from "@/components/NavBar";

export default function Home() {
  let breatheAnimationContainer = createRef();

  useEffect(() => {
    const breatheAnim = lottie.loadAnimation({
      container: breatheAnimationContainer.current,
      rerender: "svg",
      loop: true,
      autoplay: true,
      path: "/animations/breathe-data.json",
    });

    return () => breatheAnim.destroy();
  }, []);

  const router = useRouter();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div className={styles.breatheAnimation} ref={breatheAnimationContainer} />
        <NavBar/>
      </main>
    </>
  );
}